# Generated by Django 3.2.5 on 2021-09-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequestrezult',
            old_name='pullRequest',
            new_name='titile',
        ),
    ]
